In [2]:
import pandas as pd

df = pd.read_csv("../IMDB Dataset.csv")
print(df.head())
print(df.columns)

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive
Index(['review', 'sentiment'], dtype='str')

In [3]:
df["label"] = df["sentiment"].map({
    "positive": 1,
    "negative": 0
})

In [4]:
df.head()

                                              review sentiment  label
0  One of the other reviewers has mentioned that ...  positive      1
1  A wonderful little production. <br /><br />The...  positive      1
2  I thought this was a wonderful way to spend ti...  positive      1
3  Basically there's a family where a little boy ...  negative      0
4  Petter Mattei's "Love in the Time of Money" is...  positive      1

# Create PyTorch Dataset

In [10]:
import torch
from torch.utils.data import Dataset


class MyDataset(Dataset):

    def __init__(self, dataframe, tokenizer, max_length=256):
        self.data = dataframe
        self.tokenizer = tokenizer
        self.max_length = max_length


    def __len__(self):
        return len(self.data)


    def __getitem__(self, idx):

        review = self.data.iloc[idx]["review"]
        label = self.data.iloc[idx]["label"]

        tokens = self.tokenizer(
            review,
            padding="max_length",
            truncation=True,
            max_length=self.max_length,
            return_tensors="pt"
        )

        return {
            "input_ids": tokens["input_ids"].squeeze(0),
            "attention_mask": tokens["attention_mask"].squeeze(0),
            "label": torch.tensor(label, dtype=torch.long)
        }

# Create tokenizer

In [11]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained(
    "bert-base-uncased"
)

# Create dataset and dataloader

In [ ]:
from torch.utils.data import DataLoader

dataset = MyDataset(
    df,
    tokenizer
)


loader = DataLoader(
    dataset,
    batch_size=16,
    shuffle=True
)

In [21]:
dataset.__len__()

50000

In [18]:
dataset.data

                                                  review sentiment  label
0      One of the other reviewers has mentioned that ...  positive      1
1      A wonderful little production. <br /><br />The...  positive      1
2      I thought this was a wonderful way to spend ti...  positive      1
3      Basically there's a family where a little boy ...  negative      0
4      Petter Mattei's "Love in the Time of Money" is...  positive      1
...                                                  ...       ...    ...
49995  I thought this movie did a down right good job...  positive      1
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative      0
49997  I am a Catholic taught in parochial elementary...  negative      0
49998  I'm going to have to disagree with the previou...  negative      0
49999  No one expects the Star Trek movies to be high...  negative      0

[50000 rows x 3 columns]

# Test one batch

In [13]:
batch = next(iter(loader))

print(batch["input_ids"].shape)
print(batch["attention_mask"].shape)
print(batch["label"])

torch.Size([16, 256])
torch.Size([16, 256])
tensor([1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1])

In [9]:
batch

{'input_ids': tensor([[  101,  2984, 15030,  ...,  2021,  2009,   102],
         [  101,  4962, 20578,  ...,  4099, 10214,   102],
         [  101,  2028,  1997,  ...,     0,     0,     0],
         ...,
         [  101,  2023,  2003,  ...,     0,     0,     0],
         [  101,  2023,  3185,  ...,  2320,  1996,   102],
         [  101,  2035,  1999,  ...,  1998, 23069,   102]]),
 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
         [1, 1, 1,  ..., 1, 1, 1],
         [1, 1, 1,  ..., 0, 0, 0],
         ...,
         [1, 1, 1,  ..., 0, 0, 0],
         [1, 1, 1,  ..., 1, 1, 1],
         [1, 1, 1,  ..., 1, 1, 1]]),
 'label': tensor([1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0])}

In [19]:
for batch in loader:
    print(batch)

{'input_ids': tensor([[ 101, 2339, 1996,  ..., 2000, 2037,  102],
        [ 101, 2023, 3185,  ..., 4332, 2601,  102],
        [ 101, 2990, 8379,  ...,    0,    0,    0],
        ...,
        [ 101, 3302, 2001,  ...,    0,    0,    0],
        [ 101, 1000, 6802,  ...,    0,    0,    0],
        [ 101, 2026, 6707,  ..., 2012, 2560,  102]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1]]), 'label': tensor([1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0])}
{'input_ids': tensor([[  101,  2002,  3248,  ...,     0,     0,     0],
        [  101,  1045,  2288,  ...,     0,     0,     0],
        [  101,  1996,  2143,  ...,     0,     0,     0],
        ...,
        [  101,  1998,  1996,  ...,  2156, 14744,   102],
        [  101,  2023,  2003,  ...,  1037,  7656,   102],
        [  101,  1996, 16913,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0]]), 'label': tensor([1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0])}
{'input_ids': tensor([[  101,  2000,  2216,  ...,  2009,  2134,   102],
        [  101,  1996,  2132,  ...,     0,     0,     0],
        [  101, 22116,  2003,  ...,     0,     0,     0],
        ...,
        [  101,  5186,  5675,  ...,  2067,  2005,   102],
        [  101,  1045,  2066,  ...,     0,     0,     0],
        [  101,  4406,  2116,  ...,  2107,  2019,   102]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1]]), 'label': tensor([1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1])}
{'input_ids': tensor([[  101,  2013,  2054,  ...,     0,     0,     0],
        [  101,  1045,  2001,  ...,     0,     0,     0],
        [  101,  1996,  3257,  ...,     0,     0,     0],
        ...,
        [  101,  4895, 13102,  ...,  2003,  1996,   102],
        [  101,  1045,  2074,  ...,     0,     0,     0],
        [  101,  2023,  2143,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'label': tensor([1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1])}
{'input_ids': tensor([[  101,  7570, 14910,  ...,  2242,  2840,   102],
        [  101,  1996, 11056,  ...,  2019,  9577,   102],
        [  101,  2023,  3185,  ...,     0,     0,     0],
        ...,
        [  101,  2821,  1010,  ...,  3536,  1005,   102],
        [  101,  1045,  2228,  ...,  1013,  1028,   102],
        [  101,  1045,  2001,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0]]), 'label': tensor([0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1])}
{'input_ids': tensor([[  101,  1037,  8235,  ...,     0,     0,     0],
        [  101,  2045,  2024,  ..., 11111,  8216,   102],
        [  101,  5409,  1012,  ...,     0,     0,     0],
        ...,
        [  101,  2004,  2019,  ...,     0,     0,     0],
        [  101,  1037, 20462,  ..., 15949,  1998,   102],
        [  101,  1045,  2097,  ...,  3185,  1010,   102]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1]]), 'label': tensor([1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0])}
{'input_ids': tensor([[  101,  1045,  2387,  ...,  1037,  5977,   102],
        [  101,  1000,  8797,  ...,  2412,  2488,   102],
        [  101,  1996,  2466,  ...,     0,     0,     0],
        ...,
        [  101,  8194,  1005,  ...,     0,     0,     0],
        [  101,  2009,  1005,  ..., 14550,  1996,   102],
        [  101,  2043,  2017,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0]]), 'label': tensor([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1])}
{'input_ids': tensor([[ 101, 7825, 1004,  ..., 7825, 1006,  102],
        [ 101, 2023, 4895,  ...,    0,    0,    0],
        [ 101, 1045, 2074,  ...,    0,    0,    0],
        ...,
        [ 101, 1045, 2097,  ...,    0,    0,    0],
        [ 101, 2469, 1010,  ...,    0,    0,    0],
        [ 101, 2034, 1997,  ..., 1012, 1026,  102]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1]]), 'label': tensor([1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0])}
{'input_ids': tensor([[ 101, 1045, 2428,  ...,    0,    0,    0],
        [ 101, 5587, 2571,  ...,    0,    0,    0],
        [ 101, 2023, 2428,  ...,    0,    0,    0],
        ...,
        [ 101, 1045, 3427,  ...,    0,    0,    0],
        [ 101, 2009, 2165,  ...,    0,    0,    0],
        [ 101, 2005, 2033,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'label': tensor([0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1])}
{'input_ids': tensor([[  101,  7078, 27118,  ...,     0,     0,     0],
        [  101,  1008,  1008,  ...,  2191,  1037,   102],
        [  101,  2009,  2003,  ...,  2422,  3678,   102],
        ...,
        [  101,  3087,  2025,  ...,     0,     0,     0],
        [  101,  3100,  1010,  ...,  2987,  1005,   102],
        [  101,  2028,  1997,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0]]), 'label': tensor([0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1])}
{'input_ids': tensor([[ 101, 2551, 1996,  ..., 7604, 1011,  102],
        [ 101, 2256, 2155,  ...,    0,    0,    0],
        [ 101, 2017, 2052,  ..., 1010, 2009,  102],
        ...,
        [ 101, 1996, 4799,  ...,    0,    0,    0],
        [ 101, 2009, 4269,  ...,    0,    0,    0],
        [ 101, 2342, 3993,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'label': tensor([1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0])}
{'input_ids': tensor([[  101, 10166,  1010,  ...,     0,     0,     0],
        [  101, 16392,  1010,  ..., 16340,  8898,   102],
        [  101,  2023,  3185,  ...,     0,     0,     0],
        ...,
        [  101,  2130,  3889,  ...,     0,     0,     0],
        [  101,  9826,  1010,  ...,     0,     0,     0],
        [  101,  2074,  2387,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'label': tensor([0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1])}
{'input_ids': tensor([[ 101, 1045, 5068,  ...,    0,    0,    0],
        [ 101, 1045, 2031,  ..., 2793, 3666,  102],
        [ 101, 2023, 2003,  ..., 2011, 5381,  102],
        ...,
        [ 101, 1012, 1012,  ..., 1037, 5470,  102],
        [ 101, 2216, 2413,  ...,    0,    0,    0],
        [ 101, 1996, 2034,  ..., 2044, 1000,  102]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        ...,
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1]]), 'label': tensor([0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0])}
{'input_ids': tensor([[  101, 14407,  5671,  ...,     0,     0,     0],
        [  101,  1996, 27243,  ...,  2481,  1005,   102],
        [  101,  2043,  5061,  ...,  5312,  1010,   102],
        ...,
        [  101,  1045,  2354,  ...,     0,     0,     0],
        [  101, 19597,  1010,  ...,  6720,  2000,   102],
        [  101,  1045,  2387,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0]]), 'label': tensor([0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0])}
{'input_ids': tensor([[ 101, 1996, 2126,  ..., 2006, 2019,  102],
        [ 101, 2065, 2017,  ...,    0,    0,    0],
        [ 101, 6887, 7974,  ...,    0,    0,    0],
        ...,
        [ 101, 2012, 2034,  ...,    0,    0,    0],
        [ 101, 2092, 1010,  ...,    0,    0,    0],
        [ 101, 2009, 2001,  ..., 3676, 2546,  102]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1]]), 'label': tensor([0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1])}
{'input_ids': tensor([[  101,  2049,  1037,  ...,     0,     0,     0],
        [  101,  1045,  2031,  ...,     0,     0,     0],
        [  101,  1996,  5541,  ...,     0,     0,     0],
        ...,
        [  101,  6581,  3538,  ...,     0,     0,     0],
        [  101,  1000,  2160,  ..., 10132, 16599,   102],
        [  101,  2023,  2143,  ...,  1006,  2065,   102]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1]]), 'label': tensor([1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0])}
{'input_ids': tensor([[  101,  2023,  3185,  ...,  2009,  1005,   102],
        [  101,  2045,  2003,  ...,  1024,  4261,   102],
        [  101, 10166,  1012,  ...,     0,     0,     0],
        ...,
        [  101,  1996,  2034,  ...,  1998,  1996,   102],
        [  101,  2779,  7193,  ...,  2168,  2502,   102],
        [  101,  1045,  2031,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0]]), 'label': tensor([0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0])}
{'input_ids': tensor([[ 101, 1045, 2428,  ...,    0,    0,    0],
        [ 101, 2085, 1010,  ...,    0,    0,    0],
        [ 101, 2023, 3185,  ...,    0,    0,    0],
        ...,
        [ 101, 1996, 2516,  ..., 1045, 6135,  102],
        [ 101, 2023, 2028,  ...,    0,    0,    0],
        [ 101, 5373, 1045,  ..., 2063, 1012,  102]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1]]), 'label': tensor([1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1])}
{'input_ids': tensor([[ 101, 2054, 2057,  ...,    0,    0,    0],
        [ 101, 2508, 9409,  ..., 2024, 2070,  102],
        [ 101, 3236, 2023,  ...,    0,    0,    0],
        ...,
        [ 101, 1012, 1012,  ...,    0,    0,    0],
        [ 101, 2092, 2023,  ..., 8814, 2094,  102],
        [ 101, 2672, 1045,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0]]), 'label': tensor([0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1])}
{'input_ids': tensor([[  101,  2195,  2086,  ...,  1010,  8669,   102],
        [  101,  2028,  1997,  ...,  1045,  2453,   102],
        [  101,  1996,  2200,  ...,  1998,  2018,   102],
        ...,
        [  101, 18644, 28517,  ...,  2155,  2362,   102],
        [  101,  1045,  2245,  ...,  2017,  2024,   102],
        [  101,  6506,  2001,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        ...,
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0]]), 'label': tensor([1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1])}
{'input_ids': tensor([[  101,  3383,  1010,  ...,  1010,  2025,   102],
        [  101,  1037,  2576,  ...,     0,     0,     0],
        [  101,  2028,  2071,  ..., 17322,  2015,   102],
        ...,
        [  101,  2023,  2003,  ...,  2184,  2138,   102],
        [  101,  1045,  2001,  ...,  2080,  1010,   102],
        [  101,  1045, 23952,  ..., 10638,  2040,   102]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        ...,
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1]]), 'label': tensor([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0])}
{'input_ids': tensor([[ 101, 1045, 1005,  ...,    0,    0,    0],
        [ 101, 1045, 2052,  ..., 1996, 3185,  102],
        [ 101, 2123, 1005,  ...,    0,    0,    0],
        ...,
        [ 101, 2383, 2464,  ...,    0,    0,    0],
        [ 101, 2023, 2093,  ...,    0,    0,    0],
        [ 101, 1045, 2371,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'label': tensor([0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1])}
{'input_ids': tensor([[ 101, 2045, 1005,  ..., 1037, 2843,  102],
        [ 101, 1998, 2672,  ..., 3057, 2203,  102],
        [ 101, 1045, 2387,  ..., 2077, 2183,  102],
        ...,
        [ 101, 1045, 2031,  ...,    0,    0,    0],
        [ 101, 2472, 1998,  ..., 2172, 2067,  102],
        [ 101, 2023, 2003,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0]]), 'label': tensor([0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0])}
{'input_ids': tensor([[ 101, 2412, 2144,  ...,    0,    0,    0],
        [ 101, 2205, 2919,  ...,    0,    0,    0],
        [ 101, 2023, 3185,  ...,    0,    0,    0],
        ...,
        [ 101, 2049, 2428,  ..., 2073, 2010,  102],
        [ 101, 6659, 3772,  ...,    0,    0,    0],
        [ 101, 2025, 2200,  ..., 1997, 2822,  102]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1]]), 'label': tensor([1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0])}
{'input_ids': tensor([[  101,  2043, 19996,  ...,  4178,  2024,   102],
        [  101,  2023,  2143,  ...,  1026,  7987,   102],
        [  101,  2070,  2453,  ...,     0,     0,     0],
        ...,
        [  101,  2034,  1997,  ...,     0,     0,     0],
        [  101,  1996,  3152,  ...,  2097,  3193,   102],
        [  101,  2003,  2009,  ...,  1037,  2406,   102]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1]]), 'label': tensor([1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0])}
{'input_ids': tensor([[  101,  2054,  1037,  ...,  6581,  3424,   102],
        [  101,  1999,  2019,  ...,     0,     0,     0],
        [  101,  2823,  1010,  ...,  5988,  2412,   102],
        ...,
        [  101, 11721,  3489,  ...,  1012,  1006,   102],
        [  101,  1996, 10309,  ...,  1010,  2013,   102],
        [  101,  2045,  2024,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        ...,
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0]]), 'label': tensor([0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1])}
{'input_ids': tensor([[  101, 16806, 28826,  ...,  8275,  1010,   102],
        [  101,  2028,  1997,  ...,     0,     0,     0],
        [  101,  2004,  1037,  ...,  2666, 12423,   102],
        ...,
        [  101,  1048,  1005,  ...,  1996,  5896,   102],
        [  101,  1045,  2064,  ...,  6499, 13247,   102],
        [  101,  1996,  5425,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        ...,
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0]]), 'label': tensor([0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0])}
{'input_ids': tensor([[ 101, 1045, 2123,  ..., 1997, 2054,  102],
        [ 101, 1045, 2387,  ...,    0,    0,    0],
        [ 101, 3566, 2323,  ..., 5312, 2000,  102],
        ...,
        [ 101, 2339, 2106,  ..., 2016, 2001,  102],
        [ 101, 2054, 1037,  ...,  999,  102,    0],
        [ 101, 2200, 4326,  ...,    0,    0,    0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        ...,
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'label': tensor([1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0])}
{'input_ids': tensor([[  101,  2004,  2028,  ...,     0,     0,     0],
        [  101,  2023,  3185,  ...,  2611,  1012,   102],
        [  101,  3025, 12027,  ...,     0,     0,     0],
        ...,
        [  101,  1000,  4768,  ...,     0,     0,     0],
        [  101,  2129,  2000,  ...,     0,     0,     0],
        [  101,  7091,  1024,  ...,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]]), 'label': tensor([1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0])}
{'input_ids': tensor([[  101,  2043,  2017,  ..., 27242,  1012,   102],
        [  101,  2073,  1996,  ...,     0,     0,     0],
        [  101,  1045,  2228,  ...,     0,     0,     0],
        ...,
        [  101,  1045,  2018,  ...,     0,     0,     0],
        [  101,  2045,  2024,  ...,  1999,  1037,   102],
        [  101,  2017,  1005,  ...,  2088,  1000,   102]]), 'attention_mask': tensor([[1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1]]), 'label': tensor([1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0])}